name: Build and Deploy Docker Image

on:
  # schedule:
    # - cron: '*/5 * * * *'
    # - cron: '55 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 自定义环境变量，有风险危险调用，有什么私密变量请不要定义在这里
env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.actor }}/docker-arch-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect builder
        run: |
          echo "Builder info:"
          echo "Name: ${{ steps.buildx.outputs.name }}"
          echo "Endpoint: ${{ steps.buildx.outputs.endpoint }}"

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
