name: Prune Old Workflow Runs

on:
  workflow_dispatch:
  # Uncomment below to schedule weekly pruning on Sunday at 00:30 UTC
  # schedule:
  #   - cron: '30 0 * * 0'

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
